---
- hosts: localhost
  gather_facts: no
  vars:
    docker_volume: db_data
    docker_network: ansible_net
    db_name: db
    wp_name: wordpress
    wp_host_port: 8000
    wp_container_port: 80
  tasks:
    - name: "Create a Volume"
      docker_volume:
        name: "{{ docker_volume }}"

    - name: "Create a network"
      docker_network:
        name: "{{ docker_network }}"

    - name: "Launch database container"
      docker_container:
        name: "{{ db_name }}"
        image: mysql:5.7
        volumes:
          - "{{ docker_volume }}:/var/lib/mysql:rw"
        restart: true
        networks:
          - name: "{{ docker_network }}"
            aliases: "{{ db_name }}"
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
      register: mysql_container

    - set_fact:
        mysql_container_id: "{{ mysql_container.ansible_facts.docker_container.Id }}"

    - debug:
        var: mysql_container_id

    - name: Create db in mysql
      command: docker exec {{ mysql_container_id }} mysql -e "CREATE DATABASE wordpress;"
      ignore_errors: yes

    - name: Create user in mysql
      command: docker exec {{ mysql_container_id }} mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'wordpress';"
      ignore_errors: yes

    - name: Create user in mysql
      command: docker exec {{ mysql_container_id }} mysql -e "CREATE USER 'wordpress'@'%' IDENTIFIED BY 'wordpress';"
      ignore_errors: yes

    - name: Grant privilages in mysql
      command: docker exec {{ mysql_container_id }} mysql -e 'GRANT ALL PRIVILEGES ON *.* TO 'wordpress'@'localhost' WITH GRANT OPTION;'
      ignore_errors: yes

    - name: Grant privilages in mysql
      command: docker exec {{ mysql_container_id }} mysql -e 'GRANT ALL PRIVILEGES ON *.* TO 'wordpress'@'%' WITH GRANT OPTION;'
      ignore_errors: yes

    - name: "Launch wordpress container"
      docker_container:
        name: "{{ wp_name }}"
        image: wordpress:latest
        ports:
          - "80:80"
        restart: true
        networks:
          - name: "{{ docker_network }}"
            aliases: "{{ wp_name }}"
        env:
          WORDPRESS_DB_HOST: "{{ db_name }}:3306"
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress

 
